export const blogKeywords = [
  "read blog post",
  "rate blog",
  "comment on blog",
  "share blog post",
  "like article",
  "clap article",
  "highlight text",
  "bookmark result",
  "vote poll",
  "choose top benefit",
  "rank product features",
  "write 50-word review",
  "give star rating",
  "summarize content",
  "share quote",
  "copy blog URL",
  "review whitepaper",
  "annotate PDF",
  "leave comment",
  "subscribe to blog",
  "follow Medium publication",
  "applaud on Medium",
  "view landing page",
  "read case study",
  "open case study",
  "download guide",
  "scroll full article",
  "rate blog content",
  "recommend blog post",
  "click internal link",
  "check related articles",
  "read author bio",
  "comment with insight",
  "ask a question",
  "share to Facebook",
  "share to Twitter",
  "share to LinkedIn",
  "mention in your blog",
  "link back to post",
  "tag author on Twitter",
  "submit feedback",
  "suggest improvement",
  "flag typo",
  "bookmark article",
  "review blog layout",
  "rate readability",
  "save to reading list",
  "check blog tags",
  "follow blog RSS",
  "copy blog excerpt",
  "react to post",
  "select favorite blog",
  "rate by usefulness",
  "rate by clarity",
  "rate by depth",
  "rate writing style",
  "summarize paragraph",
  "summarize blog key points",
  "mark helpful post",
  "choose blog category",
  "tag blog topic",
  "comment emoji",
  "recommend to friend",
  "email blog post",
  "DM post link",
  "watch embedded video",
  "read embedded tweet",
  "click affiliate link",
  "comment on embedded media",
  "view infographic",
  "share infographic",
  "submit comment reply",
  "reply to blog comment",
  "mention blog in forum",
  "mention blog in group",
  "post blog in Facebook group",
  "discuss blog on Reddit",
  "write LinkedIn post about blog",
  "rate CTA effectiveness",
  "rate title clickbait",
  "evaluate headline",
  "suggest new title",
  "pick favorite section",
  "quote blog on Twitter",
  "tag blog hashtag",
  "save blog to Pocket",
  "save blog to Notion",
  "save blog to Evernote",
  "annotate article PDF",
  "rate SEO score",
  "check keyword density",
  "comment with timestamp",
  "create blog summary",
  "rate blog author",
  "submit grammar fix",
  "comment with personal story",
  "comment with example",
  "rate credibility",
  "suggest related topic",
  "comment with question",
];
