import RenderStatus from "@/components/table/RenderStatus";

export const columns = [
  { field: "pageTitle", headerName: "Page Title", flex: 1.5, minWidth: 200 },
  {
    field: "status",
    headerName: "Status",
    flex: 0.5,
    // minWidth: 80,
    renderCell: (params) => RenderStatus(params.value),
  },
  {
    field: "users",
    headerName: "Users",
    headerAlign: "right",
    align: "right",
    flex: 1,
    // minWidth: 80,
  },
  {
    field: "eventCount",
    headerName: "Event Count",
    headerAlign: "right",
    align: "right",
    flex: 1,
    // minWidth: 100,
  },
  {
    field: "viewsPerUser",
    headerName: "Views per User",
    headerAlign: "right",
    align: "right",
    flex: 1,
    // minWidth: 120,
  },
  {
    field: "averageTime",
    headerName: "Average Time",
    headerAlign: "right",
    align: "right",
    flex: 1,
    // minWidth: 100,
  },
];

export const rows = [
  {
    id: 1,
    pageTitle: "Homepage Overview",
    status: "Online",
    eventCount: 8345,
    users: 212423,
    viewsPerUser: 18.5,
    averageTime: "2m 15s",
  },
  {
    id: 2,
    pageTitle: "Product Details - Gadgets",
    status: "Online",
    eventCount: 5653,
    users: 172240,
    viewsPerUser: 9.7,
    averageTime: "2m 30s",
  },
  {
    id: 3,
    pageTitle: "Checkout Process - Step 1",
    status: "Offline",
    eventCount: 3455,
    users: 58240,
    viewsPerUser: 15.2,
    averageTime: "2m 10s",
  },
  {
    id: 4,
    pageTitle: "User Profile Dashboard",
    status: "Online",
    eventCount: 112543,
    users: 96240,
    viewsPerUser: 4.5,
    averageTime: "2m 40s",
  },
  {
    id: 5,
    pageTitle: "Article Listing - Tech News",
    status: "Offline",
    eventCount: 3653,
    users: 142240,
    viewsPerUser: 3.1,
    averageTime: "2m 55s",
  },
  {
    id: 6,
    pageTitle: "FAQs - Customer Support",
    status: "Online",
    eventCount: 106543,
    users: 15240,
    viewsPerUser: 7.2,
    averageTime: "2m 20s",
  },
  {
    id: 7,
    pageTitle: "Product Comparison - Laptops",
    status: "Offline",
    eventCount: 7853,
    users: 32240,
    viewsPerUser: 6.5,
    averageTime: "2m 50s",
  },
  {
    id: 8,
    pageTitle: "Shopping Cart - Electronics",
    status: "Online",
    eventCount: 8563,
    users: 48240,
    viewsPerUser: 4.3,
    averageTime: "3m 10s",
  },
  {
    id: 9,
    pageTitle: "Payment Confirmation - Bank Transfer",
    status: "Offline",
    eventCount: 4563,
    users: 18240,
    viewsPerUser: 2.7,
    averageTime: "3m 25s",
  },
  {
    id: 10,
    pageTitle: "Product Reviews - Smartphones",
    status: "Online",
    eventCount: 9863,
    users: 28240,
    viewsPerUser: 5.1,
    averageTime: "3m 05s",
  },
  {
    id: 11,
    pageTitle: "Subscription Management - Services",
    status: "Offline",
    eventCount: 6563,
    users: 24240,
    viewsPerUser: 4.8,
    averageTime: "3m 15s",
  },
  {
    id: 12,
    pageTitle: "Order Tracking - Shipments",
    status: "Online",
    eventCount: 12353,
    users: 38240,
    viewsPerUser: 3.5,
    averageTime: "3m 20s",
  },
  {
    id: 13,
    pageTitle: "Customer Feedback - Surveys",
    status: "Offline",
    eventCount: 5863,
    users: 13240,
    viewsPerUser: 2.3,
    averageTime: "3m 30s",
  },
  {
    id: 14,
    pageTitle: "Account Settings - Preferences",
    status: "Online",
    eventCount: 7853,
    users: 18240,
    viewsPerUser: 3.2,
    averageTime: "3m 15s",
  },
  {
    id: 15,
    pageTitle: "Login Page - Authentication",
    status: "Offline",
    eventCount: 9563,
    users: 24240,
    viewsPerUser: 2.5,
    averageTime: "3m 35s",
  },
  {
    id: 16,
    pageTitle: "Promotions - Seasonal Sales",
    status: "Online",
    eventCount: 13423,
    users: 54230,
    viewsPerUser: 7.8,
    averageTime: "2m 45s",
  },
  {
    id: 17,
    pageTitle: "Tutorials - How to Guides",
    status: "Offline",
    eventCount: 4234,
    users: 19342,
    viewsPerUser: 5.2,
    averageTime: "3m 05s",
  },
  {
    id: 18,
    pageTitle: "Blog Posts - Tech Insights",
    status: "Online",
    eventCount: 8567,
    users: 34234,
    viewsPerUser: 6.3,
    averageTime: "2m 50s",
  },
  {
    id: 19,
    pageTitle: "Events - Webinars",
    status: "Offline",
    eventCount: 3456,
    users: 19234,
    viewsPerUser: 4.5,
    averageTime: "3m 20s",
  },
  {
    id: 20,
    pageTitle: "Support - Contact Us",
    status: "Online",
    eventCount: 6734,
    users: 27645,
    viewsPerUser: 3.9,
    averageTime: "2m 55s",
  },
];
