import { createApi } from "@reduxjs/toolkit/query/react";
import baseQuery, { baseQueryLiveSupport } from "./baseQuery";

export const apiSlice = createApi({
  reducerPath: "api",
  baseQuery,
  endpoints: () => ({}),
  tagTypes: [
    "profile",
    "Faq",
    "Categories",
    "SubCategories",
    "ongoingTicketBuyerList",
    "DrawList",
    "getDrawSettings",
    "drawWinners",
    "getGenarelSetting",
    "updateGenarelSetting",
    "Continents",
    "countries",
    "jobs",
    "ongoingTicketBuyerList",
    "DrawList",
    "getDrawSettings",
    "drawWinners",
    "withdrawRequest",
    "depositRequest",
    "users",
    "premiumFeatures",
    "pending-users",
    "transactionHistory",
    "advertisement",
    "premiumFeatures",
    "ticket",
    "user",
    "pending-jobs",
    "getAllCostList",
    "getSiteData",
    "getIndex",
    "paymentGateway",
    "transactionData",
    "blogs",
    "blog",
    "pending-deactivations",
    "bank-transfer-deposit",
    "bank-transfer-withdraw",
    "crypto-transfer-deposit",
    "crypto-transfer-withdraw",
    "mobile-banking-deposit",
    "mobile-banking-withdraw",
    "pending-withdraw-count",
    "pending-deposit-count",
    "manager",
    "manager-details",
    "job-reports",
    "job-submissions",
    "job-single-submissions",
    "currencyConversionRate",
    "apay-deposit-transactions",
    "single-deposit-transaction",
    "apay-withdraw-transactions",
    "single-withdraw-transaction",
    "transactionQuery",
    "withdraw-history",
    "deposit-history",
    "transaction-history-query-options",
    "services",
    "announcements",
  ],
});

export const liveSupportApiSlice = createApi({
  reducerPath: "liveSupportApi",
  baseQuery: baseQueryLiveSupport,
  tagTypes: ["liveSupport", "conversation"],
  endpoints: () => ({}),
});
